### ISSUE TITLE
new torch compatibility

### ISSUE THREAD

**Issue by gsgoldma** [enlyth/sd-webui-riffusion#17]
people are being prompted on automatic1111 to update torch, it's causing conflicts with this app, breaking the program. have to reinstall venv without the extension present to fix it currently

**Comment by DGdev91** [comment]
I guess the problem here is that the installation script hasn't any mechanism to check if torch is arleady installed, and also tries to install an older version.
I tried the plugin using the newer version (even if i'm using an AMD gpu) and there shouldn't be any technical reason to keep torch version outdated.

I've created a pull request wich should solve the problem
https://github.com/enlyth/sd-webui-riffusion/pull/18

**Comment by enlyth** [comment]
Thanks @DGdev91 I've been really busy with IRL stuff lately, merged
